export enum Permission {
  VIEW_INITIATIVE = 'VIEW_INITIATIVE',
  EDIT_INITIATIVE = 'EDIT_INITIATIVE',
  DELETE_INITIATIVE = 'DELETE_INITIATIVE',
  CREATE_INITIATIVE = 'CREATE_INITIATIVE',

  VIEW_OKR = 'VIEW_OKR',
  EDIT_OKR = 'EDIT_OKR',
  DELETE_OKR = 'DELETE_OKR',
  CREATE_OKR = 'CREATE_OKR',

  VIEW_KR = 'VIEW_KR',
  EDIT_KR = 'EDIT_KR',
  DELETE_KR = 'DELETE_KR',
  CREATE_KR = 'CREATE_KR',

  EDIT_PRIORITY = 'EDIT_PRIORITY',

  INSIGHT = 'INSIGHT',
}
